apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
   replicas: 3
   selector:
     matchLabels:
       app: conversaotemperatura
   template:
     metadata:
       labels:
         app: conversaotemperatura
     spec:
       containers:
         - name: conversaotemperatura
           image: luismartorano/conversaotemperatura:latest
           ports:
             - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec: 
  selector: 
    app: conversaotemperatura
  ports:
<<<<<<< HEAD
    - port: 8080 #mesma porta q está em cluster.yaml
=======
    - port: 80
      targetPort: 8080
>>>>>>> 3c2965ffb63fc59c5d3b549888cfb9a2cc5c4ce6
      protocol: TCP
      name: http
      #nodePort: 30000
  type: LoadBalancer

